In [2]:
import pandas as pd

In [3]:
data  = pd.read_csv("./02-candidate_features_cluster.tsv",sep='\t')

In [4]:
skill_data = data[data.cluster==25] 
skill_data

                                   feature  cluster       type
1245               highly scalable systems       25  knowledge
1246                    highly scalable cv       25  knowledge
1247                 highly scalable cv ml       25  knowledge
1248                 highly scalable large       25  knowledge
1249      highly scalable large enterprise       25  knowledge
1250                in highly scalable and       25  knowledge
1251           highly scalable systems and       25  knowledge
1252                    in highly scalable       25  knowledge
1253            fast moving highly capable       25  knowledge
1254        experienced in highly scalable       25  knowledge
1255                    highly capable and       25  knowledge
1256        engineering of highly scalable       25  knowledge
1257             highly scalable and large       25  knowledge
1258           delivering well tested high       25  knowledge
1259      highly capable and collaborative       25  knowledge
1260          highly scalable and reliable       25  knowledge
1261             high quality scalable and       25  knowledge
1262  experience designing highly scalable       25  knowledge
1263         for designing highly scalable       25  knowledge
1264  probability comfortable writing high       25  knowledge
1265      comfortable writing high quality       25  knowledge
1266              comfortable writing high       25  knowledge
1267         designing highly scalable and       25  knowledge
1268       designing highly scalable large       25  knowledge
1269              deliver high quality and       25  knowledge
1270         deliver high quality software       25  knowledge
1271                    of highly scalable       25  knowledge
1272           build high quality scalable       25  knowledge
1273                        highly capable       25  knowledge
1274            of highly scalable systems       25  knowledge
1275    implement highly scalable computer       25  knowledge
1276                 moving highly capable       25  knowledge
1277                          deliver high       25  knowledge
1278                  deliver high quality       25  knowledge
1279        deliver high quality solutions       25  knowledge
1280                       highly scalable       25  knowledge
1281              deliver intelligent high       25  knowledge
1282      deliver intelligent high quality       25  knowledge
1283                 comfortable with high       25  knowledge
1284          comfortable with high degree       25  knowledge
1285             are comfortable with high       25  knowledge
1286            high degree of uncertainty       25  knowledge
1287                 high quality scalable       25  knowledge
1288             implement highly scalable       25  knowledge
1289              highly scalable computer       25  knowledge
1290         highly scalable deep learning       25  knowledge
1291         and implement highly scalable       25  knowledge
1292                   highly scalable and       25  knowledge
1293      developing high quality scalable       25  knowledge
1294             moving highly capable and       25  knowledge
1295     highly technical field experience       25  knowledge
1296         highly flexible and adaptable       25  knowledge
1297         deliver high quality accurate       25  knowledge
1298   deliver highly engineered photonics       25  knowledge
1299                  highly scalable deep       25  knowledge
1300             designing highly scalable       25  knowledge
1301             deliver highly engineered       25  knowledge
1302                        deliver highly       25  knowledge
1303       highly scalable computer vision       25  knowledge
1304       high quality scalable platforms       25  knowledge

In [5]:
from nltk.corpus import wordnet as wn

In [6]:
wn.synsets('math')

[Synset('mathematics.n.01')]

In [7]:
wn.synsets('arithmetic')[0].topic_domains()

[Synset('mathematics.n.01')]

In [10]:
#from __builtin__ import sum
skill_data['synsets'] = skill_data.feature.map(lambda x: wn.synsets(x.strip("_").split()[-2]))

C:\Users\FRE\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [11]:
skill_data

,feature,cluster,type,synsets
1245,highly scalable systems,25,knowledge,[Synset('scalable.a.01')]
1246,highly scalable cv,25,knowledge,[Synset('scalable.a.01')]
1247,highly scalable cv ml,25,knowledge,"[Synset('curriculum_vitae.n.01'), Synset('one_..."
1248,highly scalable large,25,knowledge,[Synset('scalable.a.01')]
1249,highly scalable large enterprise,25,knowledge,"[Synset('large.n.01'), Synset('large.a.01'), S..."
1250,in highly scalable and,25,knowledge,[Synset('scalable.a.01')]
1251,highly scalable systems and,25,knowledge,"[Synset('system.n.01'), Synset('system.n.02'),..."
1252,in highly scalable,25,knowledge,"[Synset('highly.r.01'), Synset('highly.r.02'),..."
1253,fast moving highly capable,25,knowledge,"[Synset('highly.r.01'), Synset('highly.r.02'),..."
1254,experienced in highly scalable,25,knowledge,"[Synset('highly.r.01'), Synset('highly.r.02'),..."
1255,highly capable and,25,knowledge,"[Synset('capable.a.01'), Synset('capable.s.02'..."
1256,engineering of highly scalable,25,knowledge,"[Synset('highly.r.01'), Synset('highly.r.02'),..."
1257,highly scalable and large,25,knowledge,[]
1258,delivering well tested high,25,knowledge,"[Synset('test.v.01'), Synset('screen.v.01'), S..."
1259,highly capable and collaborative,25,knowledge,[]
1260,highly scalable and reliable,25,knowledge,[]
1261,high quality scalable and,25,knowledge,[Synset('scalable.a.01')]
1262,experience designing highly scalable,25,knowledge,"[Synset('highly.r.01'), Synset('highly.r.02'),..."
1263,for designing highly scalable,25,knowledge,"[Synset('highly.r.01'), Synset('highly.r.02'),..."
1264,probability comfortable writing high,25,knowledge,"[Synset('writing.n.01'), Synset('writing.n.02'..."
1265,comfortable writing high quality,25,knowledge,"[Synset('high.n.01'), Synset('high.n.02'), Syn..."
1266,comfortable writing high,25,knowledge,"[Synset('writing.n.01'), Synset('writing.n.02'..."
1267,designing highly scalable and,25,knowledge,[Synset('scalable.a.01')]
1268,designing highly scalable large,25,knowledge,[Synset('scalable.a.01')]
1269,deliver high quality and,25,knowledge,"[Synset('quality.n.01'), Synset('quality.n.02'..."
1270,deliver high quality software,25,knowledge,"[Synset('quality.n.01'), Synset('quality.n.02'..."
1271,of highly scalable,25,knowledge,"[Synset('highly.r.01'), Synset('highly.r.02'),..."
1272,build high quality scalable,25,knowledge,"[Synset('quality.n.01'), Synset('quality.n.02'..."
1273,highly capable,25,knowledge,"[Synset('highly.r.01'), Synset('highly.r.02'),..."
1274,of highly scalable systems,25,knowledge,[Synset('scalable.a.01')]
1275,implement highly scalable computer,25,knowledge,[Synset('scalable.a.01')]
1276,moving highly capable,25,knowledge,"[Synset('highly.r.01'), Synset('highly.r.02'),..."
1277,deliver high,25,knowledge,"[Synset('deliver.v.01'), Synset('deliver.v.02'..."
1278,deliver high quality,25,knowledge,"[Synset('high.n.01'), Synset('high.n.02'), Syn..."
1279,deliver high quality solutions,25,knowledge,"[Synset('quality.n.01'), Synset('quality.n.02'..."
1280,highly scalable,25,knowledge,"[Synset('highly.r.01'), Synset('highly.r.02'),..."
1281,deliver intelligent high,25,knowledge,"[Synset('intelligent.a.01'), Synset('intellige..."
1282,deliver intelligent high quality,25,knowledge,"[Synset('high.n.01'), Synset('high.n.02'), Syn..."
1283,comfortable with high,25,knowledge,[]
1284,comfortable with high degree,25,knowledge,"[Synset('high.n.01'), Synset('high.n.02'), Syn..."
1285,are comfortable with high,25,knowledge,[]
1286,high degree of uncertainty,25,knowledge,[]
1287,high quality scalable,25,knowledge,"[Synset('quality.n.01'), Synset('quality.n.02'..."
1288,implement highly scalable,25,knowledge,"[Synset('highly.r.01'), Synset('highly.r.02'),..."
1289,highly scalable computer,25,knowledge,[Synset('scalable.a.01')]
1290,highly scalable deep learning,25,knowledge,"[Synset('deep.n.01'), Synset('trench.n.02'), S..."
1291,and implement highly scalable,25,knowledge,"[Synset('highly.r.01'), Synset('highly.r.02'),..."
1292,highly scalable and,25,knowledge,[Synset('scalable.a.01')]
1293,developing high quality scalable,25,knowledge,"[Synset('quality.n.01'), Synset('quality.n.02'..."
1294,moving highly capable and,25,knowledge,"[Synset('capable.a.01'), Synset('capable.s.02'..."
1295,highly technical field experience,25,knowledge,"[Synset('field.n.01'), Synset('battlefield.n.0..."
1296,highly flexible and adaptable,25,knowledge,[]
1297,deliver high quality accurate,25,knowledge,"[Synset('quality.n.01'), Synset('quality.n.02'..."
1298,deliver highly engineered photonics,25,knowledge,"[Synset('engineer.v.01'), Synset('mastermind.v..."
1299,highly scalable deep,25,knowledge,[Synset('scalable.a.01')]
1300,designing highly scalable,25,knowledge,"[Synset('highly.r.01'), Synset('highly.r.02'),..."
1301,deliver highly engineered,25,knowledge,"[Synset('highly.r.01'), Synset('highly.r.02'),..."
1302,deliver highly,25,knowledge,"[Synset('deliver.v.01'), Synset('deliver.v.02'..."
1303,highly scalable computer vision,25,knowledge,"[Synset('computer.n.01'), Synset('calculator.n..."
1304,high quality scalable platforms,25,knowledge,[Synset('scalable.a.01')]

In [12]:
skill_data['rough_tag']=skill_data.synsets.map(lambda x: x[0].name if len(x)>0 else None)

C:\Users\FRE\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [13]:
skill_data.sort('synsets',ascending=False)[['feature','rough_tag']].to_csv("./test_skills_synset", sep='\t')

AttributeError: 'DataFrame' object has no attribute 'sort'

##### from __builtin__ import sum wordnet_ids = {} for s in wn.all_synsets():     if food in sum(s.hypernym_paths(), []) and s != food:         name = s.name.split('.')[0]         wordnet_ids[s.offset] = name  print 'got', len(wordnet_ids), 'wordnet synsets'

In [12]:
df = skill_data.groupby('rough_tag').count()
df[df.feature>10].sum()

feature    870
cluster    870
type       870
synsets    870
dtype: int64

In [13]:
useful_skill_data = skill_data.sort('synsets').dropna()

In [14]:
useful_skill_data['tag'] =  useful_skill_data.rough_tag.map(lambda x: x.split(".")[0])

In [15]:
useful_skill_data.tag.value_counts().to_csv("candidate_skill_keywords_with_counts.tsv", sep='\t')

In [16]:
useful_skill_data_mapping = pd.read_csv("./candidate_skill_keywords_with_counts_and_mapping.txt", sep='\t', header=None)

In [23]:
useful_skill_data_mapping.columns = ['tag','count','final_tag']

useful_skill_data_mapping['final_tag'] = useful_skill_data_mapping.final_tag.astype('str').map(lambda x: x.strip())

In [24]:
final_skills_data = useful_skill_data.merge(useful_skill_data_mapping,on='tag').dropna().sort('count')[::-1]

In [35]:
final_skills_data[final_skills_data.final_tag == 'analytic and mathematical']

,feature,cluster,type,synsets,rough_tag,tag,count,final_tag
64,strong analytic skills,25,skills,"[Synset('analytic.a.01'), Synset('analytic.a.0...",analytic.a.01,analytic,35,analytic and mathematical
63,and analytic skills,25,skills,"[Synset('analytic.a.01'), Synset('analytic.a.0...",analytic.a.01,analytic,35,analytic and mathematical
62,responsibilities strong analytic skills,25,skills,"[Synset('analytic.a.01'), Synset('analytic.a.0...",analytic.a.01,analytic,35,analytic and mathematical
61,statistical and analytic skills,25,skills,"[Synset('analytic.a.01'), Synset('analytic.a.0...",analytic.a.01,analytic,35,analytic and mathematical
60,interpersonal and analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
59,excellent analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
58,proven analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
57,growth using analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
65,analytic skills,25,skills,"[Synset('analytic.a.01'), Synset('analytic.a.0...",analytic.a.01,analytic,35,analytic and mathematical
54,operations analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
41,business operations analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
31,expert analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
32,with excellent analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
33,others strong analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
53,quantitative and analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
34,have strong analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
35,management and analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
36,strong analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
37,using analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
38,skills demonstrated analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
39,environment strong analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
40,with sound analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
56,internally proven analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
42,extremely strong analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
49,analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
50,qualitative analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
43,sound analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
55,responsibilities strong analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
52,and analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
51,and qualitative analytical skills,25,skills,"[Synset('analytic.a.02'), Synset('analytic.a.0...",analytic.a.02,analytic,35,analytic and mathematical
...,...,...,...,...,...,...,...,...
312,management mathematical skills,25,skills,"[Synset('mathematical.a.01'), Synset('numerica...",mathematical.a.01,mathematical,22,analytic and mathematical
311,manuals mathematical skills,25,skills,"[Synset('mathematical.a.01'), Synset('numerica...",mathematical.a.01,mathematical,22,analytic and mathematical
11,aptitude math skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
12,strong retail math skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
9,good general math skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
13,retail math skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
10,good mathematics skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
16,intermediate business math skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
17,general math skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
18,have basic math skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
19,dependability general math skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
3,with good mathematics skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
8,mathematics skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
7,possess good math skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
6,business math skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
5,basic math skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
4,etc basic math skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
20,skills basic math skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
15,good math skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
21,math skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
14,high aptitude math skills,25,skills,[Synset('mathematics.n.01')],mathematics.n.01,mathematics,19,analytic and mathematical
23,writing and arithmetic skills,25,skills,"[Synset('arithmetic.n.01'), Synset('arithmetic...",arithmetic.n.01,arithmetic,3,analytic and mathematical
24,and arithmetic skills,25,skills,"[Synset('arithmetic.n.01'), Synset('arithmetic...",arithmetic.n.01,arithmetic,3,analytic and mathematical
22,arithmetic skills,25,skills,"[Synset('arithmetic.n.01'), Synset('arithmetic...",arithmetic.n.01,arithmetic,3,analytic and mathematical
1616,utilizing forecasting skill,25,skills,"[Synset('prediction.n.02'), Synset('forecast.v...",prediction.n.02,prediction,3,analytic and mathematical
1615,accordingly utilizing forecasting skill,25,skills,"[Synset('prediction.n.02'), Synset('forecast.v...",prediction.n.02,prediction,3,analytic and mathematical
649,and numerical skills,25,skills,"[Synset('numeric.s.02'), Synset('numeral.a.01'...",numeric.s.02,numeric,3,analytic and mathematical
648,numerical skills,25,skills,"[Synset('numeric.s.02'), Synset('numeral.a.01'...",numeric.s.02,numeric,3,analytic and mathematical
647,organizational and numerical skills,25,skills,"[Synset('numeric.s.02'), Synset('numeral.a.01'...",numeric.s.02,numeric,3,analytic and mathematical
1614,forecasting skill,25,skills,"[Synset('prediction.n.02'), Synset('forecast.v...",prediction.n.02,prediction,3,analytic and mathematical

In [28]:
final_skills_data.dropna().to_csv("skill_features_to_tag.tsv", sep='\t', index=None)