In [15]:
import pandas as pd
import clustering

In [2]:
skills = pd.read_csv('02-candidate_features_cluster.tsv',sep='\t')

In [3]:
skills.keys()

Index(['feature', 'cluster', 'type'], dtype='object')

In [4]:
skills.groupby('type').count()

                     feature  cluster
type
ability                   96       96
acoommodation            201      201
applicable               232      232
availability               6        6
code                     164      164
delivery                  26       26
education                378      378
experience              1892     1892
knowledge                422      422
other                    106      106
other skills             401      401
performance               61       61
previous experience      268      268
requirement               32       32
skills                  4928     4928
sponsorship               16       16
task                     333      333
work experience           67       67

In [5]:
import clustering

In [6]:
skills_skill = skills[skills['type'] == 'skills']

In [7]:
skills_skill

                                      feature  cluster    type
376                   learning and capable of       29  skills
377               learning methods experience       29  skills
378                  learning models suitable       29  skills
379          learning professional experience       29  skills
380                   deep learning knowledge       29  skills
381                 scalable machine learning       29  skills
382                    knowledge and learning       29  skills
383              learning models suitable for       29  skills
384      delivering machine learning products       29  skills
385         learn etc professional experience       29  skills
386        learning scientist with experience       29  skills
387    learning system engineering experience       29  skills
388   learning technologies proven experience       29  skills
389               delivering machine learning       29  skills
390                    learning and knowledge       29  skills
391             learning and knowledge graphs       29  skills
392                      learning and capable       29  skills
393            learning algorithms experience       29  skills
394              learning relevant experience       29  skills
395    learning techniques advanced knowledge       29  skills
396                  learning team experience       29  skills
397         learning expertise and experience       29  skills
398        learning broad robotics experience       29  skills
399            learning background experience       29  skills
400             learning and knowledge within       29  skills
401              learning hands on experience       29  skills
402                  learn quickly experience       29  skills
403               learning in depth knowledge       29  skills
404               learning library experience       29  skills
405              learning knowledge to others       29  skills
...                                       ...      ...     ...
9599       scalable computer vision solutions        0  skills
9600          scalable computer vision models        0  skills
9601            scalable computer vision deep        0  skills
9602           stack scalable computer vision        0  skills
9603            parallel computing experience        0  skills
9604                      perform in computer        0  skills
9605                    and scalable computer        0  skills
9606                  stack scalable computer        0  skills
9607              computable scenes efficient        0  skills
9608      computational complexity experience        0  skills
9609                   computer vision skills        0  skills
9610             deliverables computer vision        0  skills
9611                     limits of computable        0  skills
9612                     delivery of computer        0  skills
9613                        computable scenes        0  skills
9614                            of computable        0  skills
9615         our computer vision deliverables        0  skills
9616          highly scalable computer vision        0  skills
9617            for adaptable computer vision        0  skills
9618           looking for adaptable computer        0  skills
9619       machine computer vision experience        0  skills
9620         listening strong computer skills        0  skills
9621      or computational imaging experience        0  skills
9622      scalable computer vision algorithms        0  skills
9623        computer vision testing knowledge        0  skills
9624     computer vision libraries experience        0  skills
9625        adaptable computer vision machine        0  skills
9626     computer vision deliverables execute        0  skills
9627     or computational geometry experience        0  skills
9628                   strong computer skills        0  skills

[4928 rows x 3 columns]

In [8]:
stop_words=['skills','skill']

In [10]:
num_clusters = 20
predict = clustering.Clustering(skills_skill,num_clusters,stop_words)

Initialization complete
Iteration  0, inertia 5734.000
Iteration  1, inertia 5391.228
Iteration  2, inertia 5230.411
Iteration  3, inertia 5187.838
Iteration  4, inertia 5166.142
Iteration  5, inertia 5165.741
Converged at iteration 5: center shift 0.000000e+00 within tolerance 6.306104e-07

In [12]:
skills_skill['cluster_2'] = predict

C:\Users\FRE\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [13]:
gg = skills_skill.groupby('cluster_2')
d = clustering.get_features(gg,predict)

%reset

In [16]:
reload(clustering)

NameError: name 'reload' is not defined

In [63]:
from collections import Counter
new_tag={}

for key in range(num_clusters):
    words = clustering.BagofWords(d[key],stop_words)
#print len(d[key])
    #print words[0],words[1],words[2],words[3],words[4],len(d[key])
    #print len(d[key])
    snetlist=Counter()
    nm=min(10,len(words))
    for i in range(nm):
        
        if len(wn.synsets(words[i][0]))>0:
            snetlist[wn.synsets(words[i][0])[0].name[:-5]]+=words[i][1]
    print(sorted(snetlist.items(), key=lambda x:x[1],reverse=True)[0],sorted(snetlist.items(),
                                                                             key=lambda x:x[1],reverse=True)[1],len(d[key]))
    
    num=sorted(snetlist.items(), key=lambda x:x[1],reverse=True)[0][1]
    #if (num>=len(d[key])):
    new_tag[key] = sorted(snetlist.items(), key=lambda x:x[1],reverse=True)[0][0]+","+\
                                                sorted(snetlist.items(), key=lambda x:x[1],reverse=True)[1][0]
    #print snetlist

AttributeError: 'Counter' object has no attribute 'iteritems'

In [234]:
new_tag

{0: 'necessitate,high',
 1: 'degree,entry',
 2: 'customer,capability',
 3: 'bachelor,degree',
 4: 'work,sociable',
 5: 'continue,continually',
 6: 'prefer,secondary',
 7: 'health,science',
 8: 'associate,degree',
 9: 'patient,buttocks',
 10: 'employment,confirmation',
 11: 'need,necessitate',
 12: 'position,positive',
 13: 'institution,modification',
 14: 'merchandise,office',
 15: 'qualify,modification',
 16: 'opportunity,ongoing',
 17: 'training,train',
 18: 'adviser,consult',
 19: 'qualification,necessitate'}

In [235]:
new_tag[0]='Unknown'
new_tag[1]='Unknown'
new_tag[4]='Unknown'
new_tag[5]='Unknown'
new_tag[11]='Unknown'
new_tag[12]='Unknown'
new_tag[13]='Unknown'
new_tag[14]='Unknown'
new_tag[15]='Unknown'
new_tag[16]='Unknown'
new_tag[17]='Unknown'
new_tag[19]='Unknown'

In [369]:
new_tag=pd.DataFrame.from_dict(new_tag,orient='index')

In [370]:
new_tag = new_tag.reset_index()
new_tag.columns = ['cluster_2','new_type']

In [371]:
new_tag

    cluster_2         new_type
0           0          Unknown
1           1  product,company
2           2        technical
3           3          Unknown
4           4  product,comapny
5           5          Unknown
6           6          Unknown
7           7         friendly
8           8          Unknown
9           9          Unknown
10         10          Unknown
11         11          Unknown
12         12          Unknown
13         13        technical
14         14          Unknown

In [242]:
skills_education.keys()

Index([u'feature', u'cluster', u'type', u'cluster_2'], dtype='object')

In [241]:
skills_education.drop('New_Tag', axis=1, inplace=True)

In [244]:
skills_edu_added = new_tag.merge(skills_education)

[Synset('advisory.n.01'), Synset('advisory.s.01')]

In [246]:
set(skills_edu_added['new_type'])

{'Unknown',
 'adviser,consult',
 'associate,degree',
 'bachelor,degree',
 'customer,capability',
 'employment,confirmation',
 'health,science',
 'patient,buttocks',
 'prefer,secondary'}

In [115]:
from nltk.corpus import wordnet as wn

In [112]:
import nltk

In [251]:
skills_education.sort('cluster_2',ascending=False).to_csv("./skills_education_cluster.tsv", encoding='utf8', index=False, sep='\t')

In [120]:
wn.synsets('education')

[Synset('education.n.01'),
 Synset('education.n.02'),
 Synset('education.n.03'),
 Synset('education.n.04'),
 Synset('education.n.05'),
 Synset('department_of_education.n.01')]

In [128]:
d[2]

['education to our customers',
 'capabilities educating customers whenever',
 'pnc capabilities educating customers',
 'educating customers whenever possible',
 'new customers education',
 'customers education training',
 'educating customers whenever',
 'capabilities educating customers',
 'educating and energizing customers',
 'customer educating and',
 'of customer educating',
 'customer educating and energizing',
 'front of customer educating',
 'customers education training supports',
 'educates our customers',
 'new customers education training',
 'and new customers education',
 'educates our customers on',
 'educators and pharmacy customers',
 'customers education',
 'educate and inform customer',
 'and educate customers on',
 'additional customer education as',
 'educating customers on the',
 'educate customers and assist',
 'educate customers on the',
 'customer selection qualifications education',
 'customers feel welcome education',
 'barriers educate customers and',
 'barriers educate customers',
 'resources to educate customers',
 'provide additional customer education',
 'every customer interaction education',
 'to educate customers and',
 'customer education as needed',
 'educates the customer on',
 'educate customers track',
 'educate customers respond',
 'educate customers on options',
 'educate customers and store',
 'educate customers about officemax',
 'educate customers about',
 'educates and assists customers',
 'educating and engaging customers',
 'educate and enroll customers',
 'educate customers respond to',
 'desk while educating customers',
 'educate the customer up',
 'educating customers on rogers',
 'educating and outfitting customers',
 'educate the customer',
 'educates the customer',
 'knowledge to educate customers',
 'consultant will educate customers',
 'educate customers and',
 'educating customers on',
 'and educating customers',
 'educating customers any',
 'to educate customers',
 'additional customer education',
 'and educate customers',
 'customer interaction education',
 'customer education as',
 'customer interaction required education',
 'and educating customers any',
 'educating customers any mountain',
 'products and educating customers',
 'customer education',
 'of customer educating and',
 'accountability in educating customers',
 'while educating customers on',
 'while educating customers',
 'will educate customers',
 'will educate customers on',
 'to educate customers about',
 'products to educate customers',
 'potential barriers educate customers',
 'to educate customers track',
 'demonstrate and educate customers',
 'recipes educate customers respond',
 'recipes educate customers',
 'questions educate our customers',
 'educate our customers on',
 'assist and educate customers',
 'educate customers track store',
 'blender recipes educate customers',
 'educate our customers',
 'engaging manner educate customers',
 'educate customers on selecting',
 'manner educate customers',
 'customer educating',
 'manner educate customers on',
 'educating customers',
 'by educating customers',
 'educate and engage customers',
 'educating customers about office',
 'educate customers',
 'educate customers on',
 'by educating customers about',
 'educating customers about',
 'in educating customers on',
 'in educating customers',
 'and educates the customer',
 'and educate the customer']

In [253]:
skills_education = pd.read_csv('skills_education_cluster.tsv',sep='\t')

In [332]:
skills_knowledge = skills[skills['type'] == 'knowledge']

In [333]:
skills_knowledge

                                       feature  cluster       type
15128             knowledge and solve problems        6  knowledge
15129             knowledge and other training        6  knowledge
15130                        knowledge assists        6  knowledge
15131             knowledge and proficiency of        6  knowledge
15132              knowledge and skills within        6  knowledge
15133                knowledge and proficiency        6  knowledge
15134           knowledge assists team members        6  knowledge
15135              knowledge and relationships        6  knowledge
15136                      knowledge as needed        6  knowledge
15137                knowledge and skills with        6  knowledge
15138           knowledge and sales techniques        6  knowledge
15139             knowledge and skills desired        6  knowledge
15140           knowledge and skills excellent        6  knowledge
15141              knowledge as needed oversee        6  knowledge
15142           and attributes solid knowledge        6  knowledge
15143               knowledge base by creating        6  knowledge
15144                      knowledge and solve        6  knowledge
15145                   knowledge assists team        6  knowledge
15146                         knowledge market        6  knowledge
15147                        knowledge base by        6  knowledge
15148               knowledge of apple product        6  knowledge
15149              knowledge is helpful skills        6  knowledge
15150                    knowledge is involved        6  knowledge
15151    knowledge and relationships necessary        6  knowledge
15152              knowledge is involved takes        6  knowledge
15153                knowledge of all vehicles        6  knowledge
15154                   knowledge of all steps        6  knowledge
15155                   knowledge of all parts        6  knowledge
15156                 knowledge of all company        6  knowledge
15157                 knowledge of all aspects        6  knowledge
...                                        ...      ...        ...
20297        aptitude knowledge of residential        6  knowledge
20298        maintains basic product knowledge        6  knowledge
20299          needs develop product knowledge        6  knowledge
20300           necessary skills and knowledge        6  knowledge
20301              needs updates job knowledge        6  knowledge
20302         negotiation skills knowledge and        6  knowledge
20303  minimum qualifications knowledge skills        6  knowledge
20304                nature broad knowledge of        6  knowledge
20305              new technology knowledge of        6  knowledge
20306                 new skills and knowledge        6  knowledge
20307          list maintains strong knowledge        6  knowledge
20308   maintain professional knowledge assist        6  knowledge
20309                 maintain knowledge of up        6  knowledge
20310        achiever preferred have knowledge        6  knowledge
20311           maintain thorough knowledge of        6  knowledge
20312         mechanical aptitude knowledge of        6  knowledge
20313              maintain broad knowledge of        6  knowledge
20314              levels of product knowledge        6  knowledge
20315             managers apply pos knowledge        6  knowledge
20316              and apply product knowledge        6  knowledge
20317           maintaining sound knowledge of        6  knowledge
20318         license knowledge and experience        6  knowledge
20319          locations advanced knowledge of        6  knowledge
20320     management skills advanced knowledge        6  knowledge
20321              advanced knowledge of point        6  knowledge
20322    loan origination experience knowledge        6  knowledge
20323   management products thorough knowledge        6  knowledge
20324           maintains knowledge of banking        6  knowledge
20325     maintains strong knowledge regarding        6  knowledge
20326        managed care experience knowledge        6  knowledge

[5199 rows x 3 columns]

In [349]:
num_clusters = 15
stop_words=['knowledge']
predict = clustering.Clustering(skills_knowledge,num_clusters,stop_words)

Initialization complete
Iteration  0, inertia 4664.000
Iteration  1, inertia 4515.466
Iteration  2, inertia 4505.509
Iteration  3, inertia 4481.439
Iteration  4, inertia 4481.348
Iteration  5, inertia 4481.312
Converged at iteration 5

In [350]:
skills_knowledge['cluster_2'] = predict
gg = skills_knowledge.groupby('cluster_2')
d = clustering.get_features(gg,predict)

In [351]:
#stop_words=['general']
stop_words=['knowledge','general']

from collections import Counter
new_tag={}

for key in xrange(num_clusters):
    words = clustering.BagofWords(d[key],stop_words)
#print len(d[key])
    #print words[0],words[1],words[2],words[3],words[4],len(d[key])
    #print len(d[key])
    snetlist=Counter()
    nm=min(10,len(words))
    for i in xrange(nm):
        
        if len(wn.synsets(words[i][0]))>0:
            snetlist[wn.synsets(words[i][0])[0].name[:-5]]+=words[i][1]
    print sorted(snetlist.items(), key=lambda x:x[1],reverse=True)[0],\
                                    sorted(snetlist.items(),\
                                    key=lambda x:x[1],reverse=True)[1],\
                                    sorted(snetlist.items(), key=lambda x:x[1],reverse=True)[2],\
                                                                                    len(d[key])
    
    num=sorted(snetlist.items(), key=lambda x:x[1],reverse=True)[0][1]
    if (num>=len(d[key])):
        new_tag[key] = sorted(snetlist.items(), key=lambda x:x[1],reverse=True)[0][0]+","+\
                                                sorted(snetlist.items(), key=lambda x:x[1],reverse=True)[1][0]
    #print snetlist

('internet', 16) ('function', 15) ('functional', 12) 41
('merchandise', 584) ('expert', 13) ('skill', 13) 580
('technical', 61) ('include', 42) ('experience', 7) 101
('experience', 146) ('working', 133) ('prefer', 69) 3461
('current', 37) ('keep', 14) ('base', 3) 37
('knowing', 5) ('detail', 5) ('understanding', 3) 5
('efficaciously', 12) ('effective', 5) ('discipline', 3) 17
('knowing', 351) ('friendly', 24) ('supply', 20) 351
('use', 47) ('broad', 5) ('duty', 3) 47
('necessitate', 84) ('requirement', 27) ('skill', 18) 113
('local', 12) ('see', 3) ('plant', 1) 12
('keep', 128) ('strong', 11) ('sound', 7) 128
('occupation', 37) ('skill', 9) ('update', 4) 37
('new', 19) ('technology', 4) ('advance', 1) 19
('skill', 250) ('experience', 13) ('working', 8) 250

In [354]:
new_tag

{1: 'merchandise,expert',
 4: 'current,keep',
 5: 'knowing,detail',
 7: 'knowing,friendly',
 8: 'use,broad',
 10: 'local,see',
 11: 'keep,strong',
 12: 'occupation,skill',
 13: 'new,technology',
 14: 'skill,experience'}

In [368]:
new_tag[1]='product,company'
new_tag[4]='product,comapny'
new_tag[7]='friendly'
new_tag[13]='technical'
new_tag[2]='technical'

In [303]:
new_tag[2]='cleaning,tables'

In [304]:
new_tag[1]='MSOffice'

In [309]:
new_tag[5]='cleaning,tables'

In [367]:
for i in xrange(num_clusters):
    new_tag[i]='Unknown'

In [313]:
new_tag[2]='cleaning,tables'
new_tag[1]='MSOffice'
new_tag[5]='cleaning,tables'

In [372]:
skills_knowledge_added = new_tag.merge(skills_knowledge)

In [373]:
skills_knowledge_added

,cluster_2,new_type,feature,cluster,type
0,0,Unknown,knowledge of advertising functions,6,knowledge
1,0,Unknown,internet knowledge knowledge of,6,knowledge
2,0,Unknown,internet knowledge knowledge,6,knowledge
3,0,Unknown,internet knowledge,6,knowledge
4,0,Unknown,internet functions knowledge of,6,knowledge
5,0,Unknown,internet functions knowledge,6,knowledge
6,0,Unknown,experience and functional knowledge,6,knowledge
7,0,Unknown,functional knowledge of the,6,knowledge
8,0,Unknown,functional knowledge of,6,knowledge
9,0,Unknown,functions broad knowledge,6,knowledge
10,0,Unknown,and functional knowledge of,6,knowledge
11,0,Unknown,fundamental knowledge of internet,6,knowledge
12,0,Unknown,and functional knowledge,6,knowledge
13,0,Unknown,functions knowledge of laboratory,6,knowledge
14,0,Unknown,functions broad knowledge of,6,knowledge
15,0,Unknown,administrative functions broad knowledge,6,knowledge
16,0,Unknown,functions possess strong knowledge,6,knowledge
17,0,Unknown,knowledge of system functionality,6,knowledge
18,0,Unknown,knowledge of internet marketing,6,knowledge
19,0,Unknown,knowledge of fibre internet,6,knowledge
20,0,Unknown,and internet knowledge,6,knowledge
21,0,Unknown,and internet knowledge knowledge,6,knowledge
22,0,Unknown,and internet functions knowledge,6,knowledge
23,0,Unknown,knowledge of the internet,6,knowledge
24,0,Unknown,business functional knowledge minimum,6,knowledge
25,0,Unknown,functional knowledge,6,knowledge
26,0,Unknown,functional knowledge minimum,6,knowledge
27,0,Unknown,displays business functional knowledge,6,knowledge
28,0,Unknown,functional knowledge minimum qualifications,6,knowledge
29,0,Unknown,functional and technical knowledge,6,knowledge
...,...,...,...,...,...
5169,14,Unknown,organizational skills knowledge,6,knowledge
5170,14,Unknown,area skills knowledge understanding,6,knowledge
5171,14,Unknown,the knowledge and skills,6,knowledge
5172,14,Unknown,of knowledge skills,6,knowledge
5173,14,Unknown,skills advanced knowledge,6,knowledge
5174,14,Unknown,additional knowledge skills,6,knowledge
5175,14,Unknown,skills knowledge and,6,knowledge
5176,14,Unknown,knowledge skills strong,6,knowledge
5177,14,Unknown,knowledge skills collaborate,6,knowledge
5178,14,Unknown,management skills knowledge,6,knowledge
5179,14,Unknown,skills and knowledge in,6,knowledge
5180,14,Unknown,skills and parts knowledge,6,knowledge
5181,14,Unknown,knowledge skills and work,6,knowledge
5182,14,Unknown,knowledge or skills good,6,knowledge
5183,14,Unknown,knowledge skills collaborate with,6,knowledge
5184,14,Unknown,skills include sales knowledge,6,knowledge
5185,14,Unknown,time management skills knowledge,6,knowledge
5186,14,Unknown,knowledge base and skill,6,knowledge
5187,14,Unknown,presentation skills working knowledge,6,knowledge
5188,14,Unknown,special knowledge or skills,6,knowledge
5189,14,Unknown,skills and pc knowledge,6,knowledge
5190,14,Unknown,skills knowledge of the,6,knowledge
5191,14,Unknown,skills advanced knowledge of,6,knowledge
5192,14,Unknown,navigation skills and knowledge,6,knowledge
5193,14,Unknown,and negotiation skills knowledge,6,knowledge
5194,14,Unknown,degree preferred knowledge skills,6,knowledge
5195,14,Unknown,necessary skills and knowledge,6,knowledge
5196,14,Unknown,negotiation skills knowledge and,6,knowledge
5197,14,Unknown,minimum qualifications knowledge skills,6,knowledge
5198,14,Unknown,management skills advanced knowledge,6,knowledge

In [374]:
skills_knowledge_added.sort('cluster_2',ascending=False).to_csv("./skills_knowledge_cluster.tsv", encoding='utf8', index=False, sep='\t')